# Install Docker engine and ensure it is always running
# https://docs.docker.com/engine/install/ubuntu/
# https://medium.com/@pierangelo1982/install-docker-with-ansible-d078ad7b0a54
---
- hosts: all
  become: true
  tasks: 
    - name: install dependencies
      apt: 
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release

    - name: add GPG key
      apt_key: 
        url: https://download.docker.com/linux/ubuntu/gpg 
        state: present

    - name: add docker repository to apt
      apt_repository: 
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: install docker
      apt:
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
    
    - name: ensure docker was started and enabled
      service: 
        name: docker
        state: started
        enabled: yes

  handlers: 
    - name: restart docker
      service: 
        name: docker
        state: restarted

