---
- hosts: localhost
  become: true
  tasks: 
    - name: Install packages
      apt: 
        name: 
          - git
          - vim
          - tmux
          - bmon
          - ntpdate
          - python3-pip
          - lynx
          - rsync
          - nfs-common
          - qemu-guest-agent
    - name: copy test file
      copy: 
        src: test_file.txt
        dest: /home/ansible/test_file_success.txt

