---
- name: Configure Ubuntu servers.
  hosts: all
  become: true

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  tasks: 
    - name: Manage users and groups.
      ansible.builtin.import_tasks: tasks/users-groups.yml

    - name: Harden security with role.
      tags: [security]
      ansible.builtin.include_role:
        name: d-tork.security

    - name: Set local time zone.
      community.general.timezone:
        name: "{{ local_time_zone }}"

- ansible.builtin.import_playbook: playbooks/ssh_config.yml
- ansible.builtin.import_playbook: playbooks/etc_hosts.yml
- ansible.builtin.import_playbook: playbooks/software.yml
- ansible.builtin.import_playbook: playbooks/mounts.yml
- ansible.builtin.import_playbook: playbooks/gitconfig.yml
- ansible.builtin.import_playbook: playbooks/portainer.yml

