# Install Plex media server
# based on the role from https://galaxy.ansible.com/wilmardo/plex
---
- hosts: maeve
  roles: 
    - { role: wilmardo.plex }
  become: true
  tasks: 
    - name: enable UFW
      ufw: 
        state: enabled
    - name: open firewall for Plex
      ufw:
        rule: allow
        port: 32400
