---
# from galaxy
- name: geerlingguy.docker
- name: geerlingguy.dotfiles

# from Github
- name: d-tork.security
  src: https://github.com/d-tork/ansible-role-security
- name: d-tork.plex
  src: https://github.com/d-tork/ansible-role-plex
- name: plexupdate
  src: https://github.com/d-tork/ansible-role-plexupdate
