---
- name: Install MySQL.
  hosts: charlotte
  become: true
  vars_files:
    - ../vars/database.yml
    - ../vars/vault.yml

  roles:
    - role: geerlingguy.mysql
      vars:
        mysql_root_password: '{{ database_root_password }}'
        mysql_databases:
          - name: branker
            encoding: utf8mb4
            collation: utf8mb4_0900_ai_ci
        mysql_users:
          - name: '{{ database_user }}'
            host: "%"
            password: '{{ database_user_password }}'
            priv: "branker.*:ALL"
