# Can also potentially use https://github.com/geerlingguy/ansible-role-dotfiles
---
- name: Set up my dotfiles.
  hosts: all
  become: false
  vars_files:
    - ../vars/main.yml

  remote_user: '{{ primary_user }}'

  tasks: 
    - name: Get location of git executable.
      ansible.builtin.shell: "which git"
      register: git_location
    - name: Create config alias.
      tags: [future]
      ansible.builtin.lineinfile:
        state: present
        line: 'alias config="{{ git_location }} --git-dir=$HOME/.cfg/ --work-tree=$HOME"'
        path: "~/.bashrc"
    - name: Clone dotfiles repo.
      # TODO use ansible.builtin.git
      ansible.builtin.command: "echo cloning dotfiles repo"
    - name: Configure git user.
      # TODO use community.general.git_config
      ansible.builtin.command: "echo setting up git config"
