# Can also potentially use https://github.com/geerlingguy/ansible-role-dotfiles
---
- name: Set up my dotfiles.
  hosts: all
  become: true
  vars_files:
    - ../vars/main.yml
  vars:
    git_global_config_path: '/home/{{ primary_user }}/.gitconfig'
    dotfiles_repo_local_dir: "/home/{{ primary_user }}/dotfiles"
  remote_user: '{{ primary_user }}'

  tasks: 
    - name: Set global (user) git config.
      ansible.builtin.include_tasks: ../tasks/git_config.yml

  post_tasks:
    - name: Set user ownership of gitconfig.
      ansible.builtin.file:
        path: '{{ git_global_config_path }}'
        state: file
        owner: '{{ primary_user }}'
        group: '{{ primary_user }}'

