---
- name: Manage dotfiles with git repo as yourself.
  hosts: dolores
  roles:
    - role: geerlingguy.dotfiles
      vars:
        dotfiles_repo: "https://github.com/d-tork/dotfiles"
        dotfiles_repo_version: ubuntu
        dotfiles_repo_local_destination: '~/dotfiles'
        dotfiles_files:
          - .bash_aliases
          - .bash_profile
          - .bashrc
          - .gitignore_global
          - .inputrc
          - .tmux.conf
          - .vimrc

- name: Manage dotfiles with git repo on worker nodes.
  hosts: charlotte
  roles:
    - role: geerlingguy.dotfiles
      vars:
        dotfiles_repo: "https://github.com/d-tork/dotfiles"
        dotfiles_repo_version: ubuntu
        dotfiles_repo_local_destination: '~/dotfiles'
        dotfiles_files:
          - .bash_aliases
          - .bash_profile
          - .bashrc
          - .gitignore_global
          - .inputrc
          - .vimrc
