---
- name: Add permanent mounts.
  hosts: charlotte
  become: true

  tasks:
    - name: Add CR1B media mount. 
      ansible.posix.mount:
        src: cr1b:/media
        path: /mnt/media
        fstype: nfs4
        opts: rw,proto=tcp,port=2049
        state: mounted

    - name: Add CR4DL media mount. 
      ansible.posix.mount:
        src: cr4dl:/tank/media
        path: /mnt/tankmedia
        fstype: nfs4
        opts: defaults
        state: mounted

    - name: Add Holocron backup mount. 
      ansible.posix.mount:
        src: the-holocron:/volume1/NetBackup
        path: /mnt/holocron_backup
        fstype: nfs
        opts: rw,vers=3
        state: mounted

