---
- hosts: charlotte
  tags: [future]
  become: true
  vars:
  vars_files:
    - ../vars/portainer.yml
    - ../vars/vault.yml

  pre_tasks:
    - ansible.builtin.pip:
        name: requests
        state: present

  roles:
   - portainer
