---
- name: Install desired software.
  hosts: all
  become: true
  vars_files:
    - ../vars/main.yml

  pre_tasks: 
    - name: Update repositories.
      ansible.builtin.apt: 
        update_cache: yes
        cache_valid_time: 86400  # one day

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users: ['{{ primary_user }}']

  tasks: 
    - name: Install common software.
      ansible.builtin.apt: 
        name: 
          - git
          - vim
          - python3
          - python3-pip
          - rsync
          - nfs-common
          - qemu-guest-agent
          - net-tools
          - unattended-upgrades  # move to security role, also add open-ssh-server

    - name: Install extra software.
      tags: [extras]
      ansible.builtin.apt: 
        name: 
          - mlocate  # easier version of `find`

- name: Install python packages for control node.
  hosts: dolores
  become: false

  tasks:
    - name: Install packages with pip.
      ansible.builtin.pip:
        name:
          - passlib
          - paramiko
          - ansible-lint

- name: Install Plex server. 
  hosts: charlotte
  become: true
  vars_files:
    - ../vars/main.yml

  roles:
    - role: d-tork.plex
      vars:
        tautulli_install: false
        plexupdate_install: true
