---
- name: Install desired software.
  hosts: all
  become: true
  vars_files:
    - ../vars/main.yml

  pre_tasks:
    - name: Update repositories.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400  # one day

  roles:
    - role: geerlingguy.docker
      vars:
        docker_users: ['{{ primary_user }}']

  tasks:
    - name: Install common software.
      ansible.builtin.apt:
        name:
          - manpages-posix
          - man-db
          - bash-completion
          - git
          - vim
          - python3
          - python3-pip
          - rsync
          - nfs-common
          - qemu-guest-agent
          - net-tools
          - openssh-server
          - unattended-upgrades  # move to security role

    - name: Install extra software from repositories.
      tags: [extras]
      ansible.builtin.apt:
        name:
          - mlocate  # easier version of `find`

    - name: Install software with extra steps.
      ansible.builtin.include_tasks: ../tasks/batcat.yml


- name: Install python packages for control node.
  hosts: dolores
  become: false

  tasks:
    - name: Install packages with pip.
      ansible.builtin.pip:
        name:
          - passlib
          - paramiko
          - ansible-lint

- name: Install software specific to Charlotte.
  hosts: charlotte
  become: true
  vars_files:
    - ../vars/main.yml

  roles:
    - role: d-tork.plex
      tags: [plex, media]
      vars:
        tautulli_install: false
        plexupdate_install: true

  tasks:
    - name: Install youtube downloaders.
      ansible.builtin.import_tasks: ../tasks/youtube.yml
