---
- name: Add authorized ssh keys for incoming connections to dolores.
  tags: [security]
  hosts: dolores
  become: true

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Add authorized ssh keys from public_keys dir for my user.
      ansible.posix.authorized_key:
        user: '{{ primary_user }}'
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/dolores
        - public_keys/the-spine
        - public_keys/rehoboam
        - public_keys/the-tern
        - public_keys/the-sandpiper
        - public_keys/vimemulator
        - public_keys/arctic-tern
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted

- name: Add authorized ssh keys for incoming connections to servers.
  tags: [security]
  hosts: servers  # e.g. charlotte
  become: true

  vars_files:
    - ../vars/main.yml

  tasks:
    - name: Add authorized ssh keys from public_keys dir for ansible user.
      ansible.posix.authorized_key:
        user: ansible
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/dolores
      notify: Restart ssh

    - name: Add authorized ssh keys from public_keys dir for my user.
      # for servers, the only access point should be dolores
      ansible.posix.authorized_key:
        user: '{{ primary_user }}'
        state: present
        key: '{{ item }}'
      with_file:
        - public_keys/dolores
      notify: Restart ssh

  handlers:
    - name: Restart ssh
      ansible.builtin.service:
        name: ssh
        state: restarted

- name: Add ssh config for outgoing connections.
  hosts: dolores
  become: true
  vars_files:
    - ../vars/main.yml
  remote_user: '{{ primary_user }}'

  pre_tasks:
    - name: Ensure paramiko is installed.
      ansible.builtin.pip:
        executable: /usr/bin/pip3
        name: paramiko
        state: present

  tasks:
    - name: Add ssh connections default config.
      community.general.ssh_config:
        host: "*"
        user: '{{ primary_user }}'
        identity_file: "/home/{{ primary_user }}/.ssh/id_rsa.pub"

    - name: Add ssh connections to charlotte.
      community.general.ssh_config:
        host: charlotte
        hostname: 192.168.1.198
        user: '{{ primary_user }}'
        port: 4100
        state: present

    - name: Add ssh connections to the Spine.
      community.general.ssh_config:
        host: spine
        hostname: 192.168.1.171
        user: '{{ primary_user }}'
        state: present

    - name: Add ssh connections to Rehoboam.
      community.general.ssh_config:
        host: rehoboam
        hostname: 192.168.1.230
        user: '{{ primary_user }}'
        state: present
